### ISSUE TITLE
【邮箱黑名单】拒绝群邮件骚扰，请留私人地址

### ISSUE THREAD

**Issue by liukangxu** [apachecn/home#157]
![image](https://user-images.githubusercontent.com/1382041/58304913-de9af680-7e28-11e9-890c-2d824d9b4dcd.png)

**Comment by jiangzhonglian** [comment]
你的邮箱多少？

**Comment by jiangzhonglian** [comment]
黑名单地址收集：

fengh612@163.com

**Comment by liukangxu** [comment]
请不要将用户的个人信息（邮件地址）发布到comment中

**Comment by jiangzhonglian** [comment]
哦，好的

**Comment by liukangxu** [comment]
![image](https://user-images.githubusercontent.com/1382041/58310729-e4e59e80-7e39-11e9-918c-08066a109b42.png)
请遵守Github的TOS，谢谢！

**Comment by wizardforcel** [comment]
@liukangxu 非常抱歉，我们没有用 Github 服务发送这些邮件，也没有将它们放在仓库上，Github 无权约束我们这样做。
