### ISSUE TITLE
【邮箱黑名单】拒绝群邮件骚扰，请留私人地址

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/home#158]
黑名单地址收集：

fengh612@163.com
liukangxu1996@gmail.com
yuting0501@gmail.com
i@vgxbj.me
ztswyf@gmail.com

**Comment by YutingYou** [comment]
为什么不添加一个退订页面，体验极差。麻烦帮忙退订，谢谢：yuting0501@gmail.com

**Comment by vgxbj** [comment]
我没有订阅，请将我移出订阅列表 谢谢

i#vgxbj.me (# 替换为 @)

**Comment by KagurazakaIzumi** [comment]
未定閱過，請退訂
ztswyf@gmail.com

**Comment by wizardforcel** [comment]
@YutingYou 你要我为了这区区万分之一的投诉率，写一个系统？？没门，我今天就告诉你，没门！！

@ KagurazakaIzumi 没找到你的邮箱。
