### ISSUE TITLE
请问ApacheCN与开源组织apache.org有关系吗？

### ISSUE THREAD

**Issue by wlchn** [apachecn/home#159]
从未参加过贵组织的活动，莫名的收到了ApacheCN的加入邀请。
从未订阅过贵组织的邮件，莫名的收到了很多ApacheCN的垃圾邮件。
请问ApacheCN与开源组织apache.org有关系吗？

**Comment by jiangzhonglian** [comment]
我们和apache没有关系。
你会收到邮件，可能是你在某个领域很厉害，也愿意分享，所以才找到你。

如果你愿意，我们可以一起做装逼的事情，帮助更多的人；
如果打扰到你了，在此给你郑重的道个歉（如果是邮件的问题，还请你直接拉黑）

**Comment by fate93930** [comment]
像我这种不文明的就不客气了， @jiangzhonglian 臭傻逼

**Comment by jiangzhonglian** [comment]
【说垃圾邮件就好好说垃圾邮件，别诋毁人，OK？https://github.com/apachecn/home/issues/169 】

骂人很过瘾是吧？ 你们没人逼你，都骂出声来了。

现在这样诋毁我骂人怎么还有错呢？
![image](https://user-images.githubusercontent.com/9199175/65828095-b84f0100-e2c9-11e9-88b8-91fd025d41d3.png)

**Comment by jiangzhonglian** [comment]
【说垃圾邮件就好好说垃圾邮件，别诋毁人，OK？https://github.com/apachecn/home/issues/169 】

骂人很过瘾是吧？ 你们没人逼你，都骂出声来了。

现在这样诋毁我们组织，我骂人怎么就有错呢？
![image](https://user-images.githubusercontent.com/9199175/65828095-b84f0100-e2c9-11e9-88b8-91fd025d41d3.png)
