### ISSUE TITLE
找对象 - 片刻【长期有效】

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/home#16]
本人GitHub如下： https://github.com/jiangzhonglian

个人信息：

1. 阳光、喜欢瑜伽和课外活动（爬山除外）
2. 善良、脾气好、通情达理（不强迫人）
3. 喜欢Coding，乐于分享（自己写的教程，让很多人收益）
4. 有自己的品味，会打扮自己、喜欢拍拍美照 
5. 调皮可爱，喜欢斗图、积极乐观 
6. 现在没钱卖房子和车子，但是有着这个年龄该有的收入

对异性要求如下：

1. 阳光、不矫情
2. 善良、脾气好
3. 喜欢Coding，喜欢分享
4. 能养活自己就行

配上自己的图片，欢迎留言，我在GitHub等你
![psb](https://user-images.githubusercontent.com/9199175/43619115-d70bda40-96fe-11e8-8444-b27a020b4524.jpeg)

**Comment by vencent-love-python** [comment]
没有正面图哦，差评

**Comment by Lisanaaa** [comment]
66666！！！

**Comment by Desprado666** [comment]
99999,不是同性交友平台吗

**Comment by dualven** [comment]
需要 有图有真像~~

**Comment by daidai21** [comment]
你变了

**Comment by mj5219054** [comment]
gayhub果然名不虛傳
