### ISSUE TITLE
需要老年人加进来帮忙闲时翻译吗？

### ISSUE THREAD

**Issue by AcceptedDoge** [apachecn/home#160]
@wizardforcel 飞龙对我还有印象吗？之前翻译 Andrew 网课(B站和引进网易) 和 CS229 讲义(其他人跑了弃坑了)，我后面有一段养老时间，准备看看 @apachecn 在搞什么有趣的事情再打算冒泡，可以加入组织先隐藏着。

**Comment by AcceptedDoge** [comment]
我最近几个月可能会比较忙，在 Coursera GTC 有一个翻译项目在进行，抽空的话就过来。刚才微信转了 2.29 + 2.30 元，有寓意的。

**Comment by jiangzhonglian** [comment]
两个男孩子还玩起数字游戏，别这是你们干嘛的数字记忆？
卧槽。。 不敢想下去了，祝你们辛福

**Comment by AcceptedDoge** [comment]
> 两个男孩子还玩起数字游戏，别这是你们干嘛的数字记忆？
> 卧槽。。 不敢想下去了，祝你们辛福

神秘脑洞，我先匿了...
