### ISSUE TITLE
【运营组】咸鱼推广认领

### ISSUE THREAD

**Issue by jiangzhonglian** [apachecn/home#162]

**Comment by wizardforcel** [comment]
kaggle 机器学习实战 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602334090883&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.602334090883.1024809372&forceFlush=1

吴恩达林轩田公开课 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602127105820&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.602127105820.1024809372&forceFlush=1

小象学院 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602526847474&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.602526847474.1024809372&forceFlush=1

西瓜书花书 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=601877556787&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.601877556787.1024809372&forceFlush=1

py3入门机器学习 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602519747053&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.602519747053.1024809372&forceFlush=1

七月算法邹博 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602084457545&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567674514150.Copy.detail.602084457545.1024809372&forceFlush=1

**Comment by wizardforcel** [comment]
行业报告 https://market.m.taobao.com/app/idleFish-F2e/widle-taobao-rax/page-detail?wh_weex=true&wx_navbar_transparent=true&id=602143565942&ut_sk=1.XFZ7KilnGicDAPI7wJmhqdGS_21407387_1567692506592.Copy.detail.602143565942.1024809372&forceFlush=1

**Comment by jhdxr** [comment]
盗版他人资源可以领取DCMA takedown一个哦亲
