### ISSUE TITLE
请停止发送垃圾邮件。

### ISSUE THREAD

**Issue by wlchn** [apachecn/home#169]
Github不是你们收集用户信息，推广你们广告的地方，请停止采集用户信息，停止发送垃圾邮件。请好好的使用Github。

既然你们跟Apache Foundation没有任何关系，能不能别总打着Apache的招牌推广你们自己的东西？

**Comment by jiangzhonglian** [comment]
你要是不会说话，就滚。谁都是人，谁都有脾气！

**Comment by John-W1ck-MT** [comment]
微博，贴吧，V2慕名而来

**Comment by Yangliwei1980** [comment]
什么垃圾玩意张嘴 就叫别人滚

**Comment by Azimiao** [comment]
微博，贴吧，V2慕名而来

**Comment by python0707** [comment]
微博，贴吧，V2慕名而来

**Comment by naizut** [comment]
吃了个瓜 强势围观

**Comment by pengqiuyuan** [comment]
微博，贴吧，V2慕名而来

**Comment by KoenChiu** [comment]
V2慕名而来

**Comment by MojieBuddhist** [comment]
V2慕名而来

**Comment by gwdburst** [comment]
tg慕名而来

**Comment by jiangzhonglian** [comment]
有点意思，哈哈哈，没想到还是个有点流量的博主！

你骂人不带脏字就是文明人？

**Comment by jiangzhonglian** [comment]
请你说话下次带上情商，别上来就是诋毁别人靠着Apache招牌，
我就看看你发的文章就不带BAT国内其他打V的字样？ 什么都是你原创！

中文文档都是组织和网友贡献的，你有本事把你的东西拿出来啊！
【我也来检查一下你是否也做这种恶心的事情，粘贴别人组织或公司的字样】
【Apache在两年前就发过邮件给我们，不需要你来张嘴！】

**Comment by wizardforcel** [comment]
我们没有在 Github 上采集用户信息，也没有用 Github 来发邮件。

谁提出来谁举证谢谢。

”ApacheCN“不叫打着“Apache”的招牌，“前阿里运营”叫打着阿里的招牌。
