### ISSUE TITLE
【讨论】关于垃圾邮件我说两句吧

### ISSUE THREAD

**Issue by Zheaoli** [apachecn/home#171]
看热帖来得，并不想讨论关于 Apache 和 ApacheCN 的事，只是单纯的作为一个同样被 ApacheCN 干扰过邮箱 timeline 的人来说两句吧`

![image](https://user-images.githubusercontent.com/7054676/65828889-6a8ac680-e2d2-11e9-90a1-bd3683fe31da.png)

之前也收到 invitation ，当时也很也很莫名奇妙，后续也收到关于这个组织的很多 spam 邮件

我的态度是，既然是邀请人参与进某一个事情中，那么当初应该通过邮件或者其余方式来和邀请者达成一致后再行发送 invitation 和其余的日常运营邮件。我相信这应该是现代网络空间中应该被遵守的基本共识

而不是

> 我们和apache没有关系。
> 你会收到邮件，可能是你在某个领域很厉害，也愿意分享，所以才找到你。
> 如果你愿意，我们可以一起做装逼的事情，帮助更多的人；
> 如果打扰到你了，在此给你郑重的道个歉（如果是邮件的问题，还请你直接拉黑）

https://github.com/apachecn/home/issues/159

这样的做法，其实说实话，对于我这种不太喜欢消息噪音的人来说，这种做法其实是和每天问我要不要分期的银行电话是一个性质的。

所以大家都是文明人，按照规则办事吧，互相尊重对吧。

**Comment by diegozhu** [comment]
what a shame  ~

**Comment by laike9m** [comment]
吃瓜

**Comment by jiangzhonglian** [comment]
谢谢你的回复：
我们还是要道歉，并且垃圾邮箱的问题我们几个月前就道歉了，这个问题从反馈来说是有问题，你骂我们都可以，我们这边已经加入了退订功能，目前好像大家都没用到，我这边再去沟通沟通。

但是诋毁侵权的事情，这个事情不接受。Apache项目都有协议，我们是侵权什么呢？骂得那么凶

**Comment by eTKw** [comment]
感觉答不对题，题主的意思是希望能够在沟通并确认后再发送邀请邮件，而不是采取广撒网的形式，发送很容易让人反感的邮件。

但是回复中完全没有针对这一点说明，提到的是：1. 道歉；2. 事后手段，退订；3. 另一件事疑似碰瓷的辩解……

**Comment by Zheaoli** [comment]
> 我们还是要道歉，并且垃圾邮箱的问题我们几个月前就道歉了，这个问题从反馈来说是有问题，你骂我们都可以，我们这边已经加入了退订功能，目前好像大家都没用到，我这边再去沟通沟通。

@jiangzhonglian 怎么说，能意识到自己的问题是好事，但是作为题主，，我还是更希望，在我和这个 org 没有发生实质性的关联之前，不需要收到 spam ，然后自己处理。我相信这是对彼此的尊重。。

> 但是诋毁侵权的事情，这个事情不接受。Apache项目都有协议，我们是侵权什么呢？骂得那么凶

一开始我也说了，我并不想讨论关于这件事有所讨论，因为我不是学法的，我对于商标的相关法律（Apache 所在的美国，贵组织所在的中国大陆）的适用范围及其条款并不熟悉，所以不敢妄言。不过我刚刚也向 Apache 法律团队发了邮件来咨询我对于这方面的疑惑。

**Comment by jiangzhonglian** [comment]
现在的问题不是你说的这么简单。。【现在是吃瓜群众太多，上升了问题的性质啊！哥哥】

我说垃圾邮件的事情，大家扯侵权；我说侵权的事情，又说我在狡辩。。这都是有开源项目协议的！


垃圾有垃圾邮件，诋毁侵权是侵权 【这是2件事情】

1.垃圾邮件的事情，我们道歉，这个的确是有些问题，从你们的反馈而言！

2.但是侵权，你告诉我，我们侵权了什么？？
Apache的项目没有协议嘛？我们没遵守嘛？还是怎么呢？？


我说的任何话都成了辩解，你觉得这样聊天能聊下去吗？
我说的话为什么就不能是对的呢？怎么就成了辩解呢？

**Comment by jiangzhonglian** [comment]
这个Apache的问题，我们和Apache有过邮件，也感谢你这么热心。

你也看到了，我说什么，总有人否定。你这话不是你一个人的问题，已经上升了性质

**Comment by Zheaoli** [comment]
既然讨论到了这个，首先其实这个事其实和 license 没有关系。。而是 Apache 这个商标及附属商标的所属权的问题。

ApacheCN 从自然语义上来讲，贴近于 Apache China 这样一个现象是既定事实。无论贵组织建立之初是无意还是有意，取出这样一个名字事实上是存在侵犯他人权益的嫌疑。即便是在中国这种相对宽松的环境，这样判例其实也是不少的，我记得14年和16年都有判例最后引起高院对商标相关法律作出司法解释的，当然如果有兴趣可以单开个 issue 讨论下

所以单纯聊聊这事，就一个利益不相关的群众而言。还是建议改名避免不必要的法律风险

**Comment by Zheaoli** [comment]
另外多说一句，关于这个 

https://github.com/apachecn/home/issues/162

issue 下的一些操作，可能会涉及到违反版权。我已经联系图灵和人邮那边确认下这个行为具体的情况了

**Comment by jiangzhonglian** [comment]
真的非常感谢你们这些热心的人

**Comment by jiangzhonglian** [comment]
现在问题，我早就说了，不是垃圾邮件的事情。
这就是要搞事情嘛！说的那么好听，哈哈哈😂我佩服你们这些文化人

**Comment by wizardforcel** [comment]
@Zheaoli 不构成侵权的案例好像更多，比如新东方教育和新东方厨师培训，百度搜索和百度烤肉。

不过谢谢你的提醒，我们会尽快把注册商标这事提上日程。
