### ISSUE TITLE
订阅平台提示该用户未订阅

### ISSUE THREAD

**Issue by KexyBiscuit** [apachecn/home#177]
此前收到邮件，看到霸气的“请直接拉黑我们”，也没法说啥，毕竟垃圾邮件一般就是这样的。
今日再次收到月报，惊喜的发现有订阅平台了，进入输入邮箱后却发现直接提示该用户未订阅。
翻了一下更旧的邮件，发现 #158 也已经锁定了。请问应该如何正确地退订贵社区的所有邮件呢？

**Comment by jiangzhonglian** [comment]
抱歉，正在问，你的邮箱多少来着？

**Comment by KexyBiscuit** [comment]
@jiangzhonglian kexybiscuit@outlook.com

**Comment by jiangzhonglian** [comment]
再次抱歉，我问过负责人，你的确没订阅，也应该不会在列表中（但是你还收到可能有点诡异）
这个业务今后会交给另外一个人，所以没订阅的理论上不会再收到。

**Comment by KexyBiscuit** [comment]
感谢！

**Comment by shiwanjun** [comment]
请问发生了什么事情


在 2019-12-06 10:34:10，"片刻" <notifications@github.com> 写道：


再次抱歉，我问过负责人，你的确没订阅，也应该不会在列表中（但是你还收到可能有点诡异）
这个业务今后会交给另外一个人，所以没订阅的理论上不会再收到。
