### ISSUE TITLE
征集：大家想要翻译 or 学习的内容

### ISSUE THREAD

**Issue by wizardforcel** [apachecn/home#59]
<https://www.apachecn.org/translate/>

**Comment by Winchester-Yi** [comment]
Learning_Deep_Architectures_for_AI，Yoshua Bengio
https://www.iro.umontreal.ca/~bengioy/papers/ftml_book.pdf

**Comment by wizardforcel** [comment]
@Winchester-Yi 

[Learning Deep Architectures for AI 中文版.pdf](https://github.com/apachecn/home/files/2363139/Learning.Deep.Architectures.for.AI.pdf)

**Comment by Yao544303** [comment]
PMML文档，拒绝只当一个掉包侠
http://dmg.org/pmml/pmml-v4-3.html

**Comment by gzgywh** [comment]
好的，谢谢，那能不能翻译一下新版本的pytorch0.4，据说跟0.3改动还挺大的https://pytorch.org/tutorials/

**Comment by wizardforcel** [comment]
@gzgywh 0.4 是过渡版本，等 1.0 的时候再翻译。

@Yao544303 这个框架太小众了，翻译出来没人看。

**Comment by xjw0914** [comment]
https://github.com/apache/incubator-airflow

**Comment by shouldsee** [comment]
pymc3的文档好像还没有中文版。。（但是我目前好像也并用不上pymc3)

**Comment by jiangzhonglian** [comment]
大佬，能不能出个关于使用公共数据集的教程

比如imagenet，coco啥的
最近想在tensorflow上搞coco数据集浪费了我好几天时间，现在还没有搞定-_-

**Comment by wizardforcel** [comment]
@gzgywh 我在他们的页面上找到了文字版的讲义。。。

DL1/2/ML 都有。Prob140 搞完就可以开始搞这个。

**Comment by littleeleventhwolf** [comment]
Druid
http://druid.io/docs/latest/design/

**Comment by Ir1d** [comment]
https://github.com/mml-book/mml-book.github.io

**Comment by z790704069** [comment]
https://hadoop.apache.org/ozone/docs/0.2.1-alpha/

**Comment by z790704069** [comment]
> https://hadoop.apache.org/ozone/docs/0.2.1-alpha/

还没有release，不知道可值得翻译

**Comment by wizardforcel** [comment]
这个 machine learning mastery 有很多很好的教程，但不是每个都值得翻译。

<https://machinelearningmastery.com/start-here/>

**Comment by wizardforcel** [comment]
algorithm archive 里面有很多数值算法

<https://github.com/algorithm-archivists/algorithm-archive>

**Comment by DuXin007** [comment]
[cuda-c-programming-guide](https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html)
[cuda-c-best-practices-guide](https://docs.nvidia.com/cuda/cuda-c-best-practices-guide/index.html)

**Comment by wizardforcel** [comment]
@DuXin007 

[CUDA 编程指南 5.0 中文版.pdf](https://github.com/apachecn/home/files/2481314/CUDA.5.0.pdf)

最佳实践指南没找到。

**Comment by littleeleventhwolf** [comment]
> Druid
> http://druid.io/docs/latest/design/

Superset
https://superset.incubator.apache.org/

**Comment by littleeleventhwolf** [comment]
> Druid
> http://druid.io/docs/latest/design/

Superset
https://superset.incubator.apache.org/

**Comment by huangxiaohui8** [comment]
龙哥，我看你翻译了伯克利的CS61A，而我们正在学习CS61B，几百个一起学的小伙伴都说这门课比CS61A实用，还要好，基本上学完CS61B之后找工作没问题，我觉得咱们翻译一下CS61B，很多其他专业转CS的小伙伴都强烈推荐

**Comment by wizardforcel** [comment]
@huangxiaohui8 好的，下一个活动就安排。

**Comment by wizardforcel** [comment]
@Jonyezog 会考虑，但是大家不是特别愿意翻译这种纯理论的东西。。。

**Comment by wizardforcel** [comment]
@huangxiaohui8 活动已开启：<https://github.com/apachecn/cs61b-textbook-zh>

**Comment by DylanFrank** [comment]
大佬们有考虑翻译这本书的吗，这是芬兰国家队教练写的，ICPC之类的比赛入门教材[Competitive Programmer's Handbook](https://cses.fi/book/index.html) https://cses.fi/book/index.html 一直没有找到中文翻译 :(

**Comment by Ir1d** [comment]
@DylanFrank 这本书内容比较基础，翻译起来价值不是很高，国内竞赛相关也有不少很好的书籍，最近也有个 OI Wiki 致力于整理相关资料

**Comment by wizardforcel** [comment]
> https://github.com/mml-book/mml-book.github.io

还有一本相似的，计算机科学的数学（mcs），也可以考虑。

**Comment by xshahq** [comment]
以太坊的黄皮书。看过一些翻译的版本都翻译的不怎么样

**Comment by wizardforcel** [comment]
NumPy 技术栈的其它工具：Seaborn

高性能 Python 库：Cython，Numba
