### ISSUE TITLE
个人捐赠：@mysteven2017 2018-11-05 微信 12.00元

### ISSUE THREAD

**Issue by mysteven2017** [apachecn/home#92]
个人捐赠： @mysteven2017 2018-11-05 微信 12元 on 5 Nov

**Comment by jiangzhonglian** [comment]
![image](https://user-images.githubusercontent.com/9199175/48038243-c7f1c280-e1aa-11e8-9876-c23abeb110eb.png)

**Comment by jiangzhonglian** [comment]
谢谢 对组织的支持
